apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helloworld-profile-cr-ms
  namespace: pkc
spec:
  interval: 1m
  chart:
    spec:
      chart: ./pkc/helmcharts/hello-world-1.0.32.tgz
      version: '1.0.32'
      sourceRef:
        kind: GitRepository
        name: ncp-app
        namespace: pkc
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: pkc
  
