kind: ConfigMap
metadata: # kpt-merge: example/network-function-values
  name: ms-values
  namespace: pkc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|network-function-values'
apiVersion: v1
data:
  values.yaml: |
    replicaCount: 2  # kpt-set: ${replicas}
    image:
      tag: latest
