
{{ if gt (int .Values.postscaleout ) 0 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "fullname" . }}-postscaleout"
spec:
  template:
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
      - name: {{ template "fullname" . }}-postscaleout
        image: "{{ .Values.global.registry }}/{{ .Values.kubectlImage }}:{{ .Values.kubectlTag }}"
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
{{ toYaml .Values.containerSecurityContext | indent 10 }}
        command:
          - sh
          - "-c"
          - |
            echo "PostScaleOut hook!"
            sleep 2
      restartPolicy: Never
{{- end }}
