apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ncm-app-kusto
  namespace: pkc
spec:
  interval: 15m
  path: ./ncm-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ncp-app
