{{- if .Values.cbur.enabled }}
{{- if .Capabilities.APIVersions.Has "cbur.csf.nokia.com/v1/BrPolicy" }}
apiVersion: "cbur.csf.nokia.com/v1"
{{- else }}
apiVersion: "cbur.bcmt.local/v1"
{{- end }}
kind: BrPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
spec:
  k8sType: deployment
  brOption: 0
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  volumes:
  #- helloworld-data   #<---volume name you want to backup. NOTE: not mount path
  - {{ template "fullname" . }}
  backend:
    mode: "local"
  cronSpec: "*/5 * * * *"
  maxiCopy: 2
  hooks:
    - name: {{ template "fullname" . }}
      commands:
        preBackupCmd: []
        postBackupCmd: []
        preRestoreCmd: []
        postRestoreCmd: []
{{- end }}
