{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $oldFormat := not (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
{{- if $oldFormat }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ printf "%s.%s.%.0f" .Release.Namespace $releaseName .Values.ingress.servicePort }}
spec:
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
        {{- if $oldFormat }}
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.ingress.servicePort }}
        {{- else }}
          service:
            name: {{ template "fullname" . }}
            port:
              number: {{ .Values.ingress.servicePort }}
        pathType: ImplementationSpecific
        {{- end }}
        path: {{ .Values.ingress.path }}
  {{- else }}
  - http:
      paths:
      - backend:
        {{- if $oldFormat }}
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.ingress.servicePort }}
        {{- else }}
          service:
            name: {{ template "fullname" . }}
            port:
              number: {{ .Values.ingress.servicePort }}
        pathType: ImplementationSpecific
        {{- end }}
        path: {{ .Values.ingress.path }}
  {{- end -}}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end -}}
{{- end -}}

