{{- if .Values.k8swait.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.k8swait.job.jobname }}"
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
spec:
  template:
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
        - name: "{{ .Values.k8swait.job.jobname }}"
          image: "{{ .Values.global.registry }}/{{ .Values.k8swait.job.repo }}:{{ .Values.k8swait.job.tag }}"
          imagePullPolicy: {{ .Values.k8swait.job.pullPolicy }}
{{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 10 }}
{{- end }}
          command:
          - /bin/sh
          - -c
          - |
            sleep 10
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 10Mi
      restartPolicy: {{ .Values.k8swait.job.restartPolicy }}
  backoffLimit: 4
{{- end }}
