{{- if .Values.pvc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "claimname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
spec:
{{- if .Values.storageclassname }}
{{- if (eq "-" .Values.storageclassname) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storageclassname }}"
{{- end }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{- end }}
