{{- if .Values.k8swait.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "fullname" . }}-admin
    namespace: "{{ .Release.Namespace }}"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ template "fullname" . }}-crolebinding
    namespace: "{{ .Release.Namespace }}"
subjects:
    - kind: ServiceAccount
      name: {{ template "fullname" . }}-admin
      namespace: "{{ .Release.Namespace }}"
roleRef:
    kind: ClusterRole
    name: admin
    apiGroup: rbac.authorization.k8s.io
{{- end }}
