apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ncm-app-ms
  namespace: pkc
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./ncm-app/helmcharts/ncm-app-2.3.2.tgz
      version: '2.3.2'
      sourceRef:
        kind: GitRepository
        name: ncp-app
        namespace: pkc
      interval: 1m
  targetNamespace: pkc
  valuesFrom:
  - kind: ConfigMap
    name: ncm-app-values
    valuesKey: values.yaml
